### ISSUE TITLE
[TASK] 台風をどうにかする

### ISSUE THREAD

**Issue by greenlaver** [ritscc/IRKit#7]
## 背景
**台風15号**が迫っている

![](https://www.jma.go.jp/jp/typh/images/zooml/1915-00.png)

## 実装要件
- [ ] 台風をどうにかする

## 説明
KC3直撃、やめてください。

**Comment by itanium-R** [comment]
無理難題で草

もしも本当に
ＫＣ３参加者の
安心安全を
考えるならば
わたくしも暴風での休講大好きですけども、
法律で台風の来日を
禁止して、
禁止すればいい（

**Comment by itanium-R** [comment]
よく学校である告知はいるよなぁ

暴風警報または気象等に関する特別警報が発令された場合もしくは気象等により交通機関が不通となった場合の本イベントの取り扱いは、下表の通りとします。
1 暴風警報または気象等に関する特別警報が午前７時００分の時点で京都府、大阪府、奈良県、滋賀県の１地域以上に発令されている場合、${中止か延期}とする。
2  JR 西日本(神戸―草津間、京都―二条間)、阪急(梅田―河原町間)、京阪、近鉄の 4 交通機関のうち、3 交通機関以上が不通の場合、${中止か延期}とする。

↑こんな感じ

**Comment by greenlaver** [comment]
普通にまともなコメントを頂けて感謝（さーせんw）
